import paramiko
import base64

def decode_base64_private_key(base64_key):
    return base64.b64decode(base64_key)

def deploy_using_ssh(private_key, server_address, remote_command):
    ssh = paramiko.SSHClient()

    try:
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # Decode the base64 private key
        private_key = paramiko.RSAKey(file_obj=paramiko.StringIO(private_key.decode('utf-8')))

        ssh.connect(server_address, username='kevin', pkey=private_key)

        stdin, stdout, stderr = ssh.exec_command(remote_command)

        print("Output:")
        print(stdout.read().decode('utf-8'))

    finally:
        ssh.close()

if __name__ == "__main__":
    # Replace with your actual base64-encoded private key, server address, and remote command
    placeholder_base64_private_key = b'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF1R2xqTmtFRVYrcmlxd0EwVlNCZnpDdXRPVWQwQktqUHZSZHpab0dhdUluWGE1MVo2enpICnRLRVcvYTkyZ0JHcy9tTTdWRld3WjYvOVp1NjBRQmtEWm9ZZE1qUDdTNjNNVFpVZytXb1hIU2VHT2Q2ZVZXRUZmNG8zVG8KSUlBK3l2TWUwdWhqZkVxakZ4aC9JWU1VWnQ1Wml6eGhUNDNrNSs4TXdLQjBLY042RU5TUVBmWHZzTmUrSkZVTnVwTnA5VgoyUXpSUGN1dDFUYktGMnFIL3VzeFpGdkJXT0pmQ2FUL2g1N1hJODN1RkpBRXdTekZmZCtUaCs3ODE5Z20raXNuNWlOYlJNCkpJTG0xZDNJV3ZXYzk1aUxmeVpoR0RlTmhPSXZlbzhsMzFGVENBYjdQVFViVFlxSCtiSFdyd0FJODUvQlNKa2ZmVWJJancKZEZhcVhQTzI2UUFBQThqZkxZd1EzeTJNRUFBQUFBZHpjMmd0Y25OaEFBQUJBUUM0YVdNMlFRUlg2dUtyQURSVklGL01LNgowNVIzUUVxTSs5RjNObWdacTRpZGRyblZuclBNZTBvUmI5cjNhQUVheitZenRVVmJCbnIvMW03clJBR1FObWhoMHlNL3RMCnJjeE5sU0Q1YWhjZEo0WTUzcDVWWVFWL2lqZE9nZ2dEN0s4eDdTNkdOOFNxTVhHSDhoZ3hSbTNsbUxQR0ZQamVUbjd3ekEKb0hRcHczb1ExSkE5OWUrdzE3NGtWUTI2azJuMVhaRE5FOXk2M1ZOc29YYW9mKzZ6RmtXOEZZNGw4SnBQK0hudGNqemU0VQprQVRCTE1WOTM1T0g3dnpYMkNiNkt5Zm1JMXRFd2tndWJWM2NoYTlaejNtSXQvSm1FWU40MkU0aTk2anlYZlVWTUlCdnM5Ck5SdE5pb2Y1c2RhdkFBanpuOEZJbVI5OVJzaVBCMFZxcGM4N2JwQUFBQUF3RUFBUUFBQVFCSGRxZTQzYWRHUHNNS1MzRDgKVUNodm9ibG1TaGRldXVDT1FhazUzeDNMUjdlUWY1RGFCVnJLMStabDl2b3dGU2w2QjVCMVZTT2dldVh6WHF2QmJ6QVBLZwpma2JacURzRjFNNzI2dzJQa09Ga1FBNXhGcXVzZDdybDlTY0RlVTljTEswVVJIUlJOVWRRYXZEUlZzK3dNWmgzeWJWWU0vCit5RmNSV1haZkdtM2NHdzdNTVJsK0pWbTZnOWJuV1VqWGdnWTM3MG9KTG5XRUdXcmltMlhqcWRqZ2dSVkJnV3ZhMDZSOGYKSGc0TUJvYVFqM1J6YmRtWjdJOW5PRERlOVJubk0zZ0lUNENJdVo4NjVnOWk1UHRUMndYd2VWUW5oK2NzMWNsckJMdHZtWQplTFQyMlArVU04QWdweEU2b1BWYVkzRzQzVUg1TnlINlVhR1paQkpKUWZabEFBQUFnRldPQWFuSE5zWTFNbEdaVWgzOHdvCjc2NTFIOFNIa25LVS9EYlhzSzArQlYwSXR4Y2dwK2M1RC84MG53ZmUrdS9UemkrcmdXbTI0QlYxNG0rcHZzcHlCazFwUkMKY0VKb3RBU1J5Wi9odjc5ZDJYT3J2SjFSMTJpS2J2cllYZW41YThRaW5xenVjL1RZS2J6MElIQVZicmZpTHFLbnpaaXhzNApMVnVqQ00zWjBVQUFBQWdRRG84V1ZjaUNWaEdIdmpDV24xVE5jMkZSU3MzcDFVMURyWjVjUDRtdFhjaDhTRjF4d1I5bnl2CjNwYnV2SnFmYXhYcHliZHRaTkw1d2NqTGdOQzJJeHF5MXBUNUFHeUJiaFB6N3haenRMQml4Um40WkFGRlNNR2RYRGN4M0MKWDdqZExEVW9VTnNheitvbVVpSjUyYmh0Y0kxM3daejlvVThtbXYyem0vRndxeUR3QUFBSUVBeXFvK2tIcmdLYS9YYXVGcQo1cjBWNnBNZEVJYU43NVI0cVBDRjhLd3BsU1pjbHNwV0luRStYYjFKVHVYTVNabXF6RFYvbjh4Yk1LVUJCZk5xS095ZUZQCnEycXlqUHladnE1T0xWdVJTdU9FM1ExeU4vZjJLNkt6UUp0UVllUnlFeFpJazYxK3NOWWRqS3lyWWlwWTRRRm4wT29CaksKM21yNTA0MmRkaWxBSDRjQUFBQVBhMlYyYVc1QWJHOWpZV3hvYjNOMEFRSURCQT09Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo='
    server_address = "localhost"
    remote_command = "echo 'Hello from the remote server!'"

    decoded_private_key = decode_base64_private_key(placeholder_base64_private_key)

    deploy_using_ssh(decoded_private_key, server_address, remote_command)
